-- =====================================================================
-- V1: Esquema base del reto tecnico Lite Thinking
-- Modelo entidad-relacion (requisito f):
--   Empresa 1-N Producto
--   Producto N-M Categoria
--   Cliente 1-N Orden
--   Orden  N-M Producto (a traves de orden_item)
--   Inventario: productos por empresa
-- =====================================================================

CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    nombre        VARCHAR(150) NOT NULL,
    rol           VARCHAR(20)  NOT NULL
);

CREATE TABLE empresa (
    nit       VARCHAR(30)  PRIMARY KEY,
    nombre    VARCHAR(150) NOT NULL,
    direccion VARCHAR(200),
    telefono  VARCHAR(50)
);

CREATE TABLE categoria (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE producto (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(50)    NOT NULL UNIQUE,
    nombre          VARCHAR(150)   NOT NULL,
    caracteristicas TEXT,
    precio_base     NUMERIC(15, 2) NOT NULL,
    moneda_base     VARCHAR(10)    NOT NULL,
    empresa_nit     VARCHAR(30)    NOT NULL REFERENCES empresa (nit) ON DELETE CASCADE
);

CREATE TABLE producto_categoria (
    producto_id  BIGINT NOT NULL REFERENCES producto (id) ON DELETE CASCADE,
    categoria_id BIGINT NOT NULL REFERENCES categoria (id) ON DELETE CASCADE,
    PRIMARY KEY (producto_id, categoria_id)
);

CREATE TABLE cliente (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(150) NOT NULL,
    email    VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(50)
);

CREATE TABLE orden (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT         NOT NULL REFERENCES cliente (id) ON DELETE CASCADE,
    fecha      TIMESTAMP      NOT NULL,
    total      NUMERIC(15, 2)
);

CREATE TABLE orden_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id        BIGINT         NOT NULL REFERENCES orden (id) ON DELETE CASCADE,
    producto_id     BIGINT         NOT NULL REFERENCES producto (id),
    cantidad        INTEGER        NOT NULL,
    precio_unitario NUMERIC(15, 2) NOT NULL
);

CREATE TABLE inventario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_nit VARCHAR(30) NOT NULL REFERENCES empresa (nit) ON DELETE CASCADE,
    producto_id BIGINT      NOT NULL REFERENCES producto (id) ON DELETE CASCADE,
    cantidad    INTEGER     NOT NULL,
    CONSTRAINT uq_inventario_empresa_producto UNIQUE (empresa_nit, producto_id)
);

CREATE INDEX idx_producto_empresa ON producto (empresa_nit);
CREATE INDEX idx_orden_cliente ON orden (cliente_id);
CREATE INDEX idx_inventario_empresa ON inventario (empresa_nit);
